defaults: &defaults
  docker:
    - image: circleci/php:7.3-node-browsers
  working_directory: ~/ataylorme-wordpress-theme
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb

version: 2

jobs:

  test_all:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - vendor-{{ checksum "composer.lock" }}
            - vendor-

      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
            - node-modules-

      - run:
          name: install PHP dependencies
          command: composer install --no-ansi --no-interaction --optimize-autoloader --no-progress

      - run:
          name: Tests PHP coding standards
          command: composer run-phpcs

      - run:
          name: Run PHP unit tests
          command: composer phpunit-dev

      - run:
          name: install Node dependencies
          command: npm ci

      - run:
          name: Run gulp linting
          command: npm run lint:gulp

      - run:
          name: Run style linting
          command: npm run lint:style

      - run:
          name: Run the dev build
          command: npm run build

      - run:
          name: Run gulp tests
          command: npm run test:gulp

      - save_cache:
          key: main-vendor-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - save_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  test:
    jobs:
      - test_all
